services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - NEO4J_AUTH=neo4j/test
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
